USE palsdb;

DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS UserType;
DROP TABLE IF EXISTS UserStatus;
DROP TABLE IF EXISTS PackSize;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS OrderStatus;